name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

-name:  Build Project
        run: npm install && npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .dist  # This deploys everything in the repository

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

